package constant

const (
	MQTT_MSG_TYPE_RESERVED    = 0
	MQTT_MSG_TYPE_CONNECT     = 1
	MQTT_MSG_TYPE_CONNECTACK  = 2
	MQTT_MSG_TYPE_PUBLISH     = 3
	MQTT_MSG_TYPE_PUBACK      = 4
	MQTT_MSG_TYPE_PUBREC      = 5
	MQTT_MSG_TYPE_PUBREL      = 6
	MQTT_MSG_TYPE_PUBCOMP     = 7
	MQTT_MSG_TYPE_SUBSCRIBE   = 8
	MQTT_MSG_TYPE_SUBACK      = 9
	MQTT_MSG_TYPE_UNSUBSCRIBE = 10
	MQTT_MSG_TYPE_UNSUBACK    = 11
	MQTT_MSG_TYPE_PINGREQ     = 12
	MQTT_MSG_TYPE_PINGRESP    = 13
	MQTT_MSG_TYPE_DISCONNECT  = 14
	MQTT_MSG_TYPE_RESERED_END = 15
)

const(
	MQTT_CONNECT_RETURN_CODE_ACCEPTED = 0
	MQTT_CONNECT_RETURN_CODE_REFUSED_PROTOCOL_VERSION = 1
	MQTT_CONNECT_RETURN_CODE_REFUSED_IDENTIFIER_REJECTED = 2
	MQTT_CONNECT_RETURN_CODE_REFUSED_SERVER_UNAVAILABLE = 3
	MQTT_CONNECT_RETURN_CODE_REFUSED_USERNAME_PASSWORD = 4
	MQTT_CONNECT_RETURN_CODE_REFUSED_NOT_AUTHORIZED = 5
)
